// code/renderers/react/src/types.ts
import type { ComponentType } from 'react';
import type { WebRenderer } from 'storybook/internal/types';

export type { RenderContext, StoryContext } from 'storybook/internal/types';

export interface ReactRenderer extends WebRenderer {
  component: ComponentType<this['T']>;
  storyResult: StoryFnReactReturnType;
}

export interface ShowErrorArgs {
  title: string;
  description: string;
}

export type StoryFnReactReturnType = JSX.Element;

// code/renderers/web-components/src/types.ts
import type { StoryContext as StoryContextBase, WebRenderer } from 'storybook/internal/types';

import type { SVGTemplateResult, TemplateResult } from 'lit';

export type StoryFnHtmlReturnType =
  | string
  | Node
  | DocumentFragment
  | TemplateResult
  | SVGTemplateResult;

export type StoryContext = StoryContextBase<WebComponentsRenderer>;

export interface WebComponentsRenderer extends WebRenderer {
  component: string;
  storyResult: StoryFnHtmlReturnType;
}

export interface ShowErrorArgs {
  title: string;
  description: string;
}
