// code/renderers/react/template/components/Pre.jsx
import React from 'react';

import PropTypes from 'prop-types';

export const Pre = ({ style = {}, object = null, text = '' }) => (
  <pre style={style} data-testid="pre">
    {object ? JSON.stringify(object, null, 2) : text}
  </pre>
);

Pre.propTypes = {
  style: PropTypes.shape({}),
  object: PropTypes.shape({}),
  text: PropTypes.string,
};

// code/frameworks/angular/template/components/pre.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'storybook-pre',
  template: `<pre data-testid="pre" [ngStyle]="style">{{ finalText }}</pre>`,
})
export default class PreComponent {
  /** Styles to apply to the component */
  @Input()
  style?: Object;

  /** An object to render */
  @Input()
  object?: Object;

  /** The code to render */
  @Input()
  text?: string;

  get finalText() {
    return this.object ? JSON.stringify(this.object, null, 2) : this.text;
  }
}
