// code/renderers/preact/template/components/Pre.jsx
/**
 * Pre component
 *
 * @param {object} props
 * @param {object} [props.style]
 * @param {object} [props.object]
 * @param {string} [props.text]
 */
export const Pre = ({ style, object, text }) => (
  <pre style={style} data-testid="pre">
    {object ? JSON.stringify(object, null, 2) : text}
  </pre>
);

// code/frameworks/angular/template/components/pre.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'storybook-pre',
  template: `<pre data-testid="pre" [ngStyle]="style">{{ finalText }}</pre>`,
})
export default class PreComponent {
  /** Styles to apply to the component */
  @Input()
  style?: Object;

  /** An object to render */
  @Input()
  object?: Object;

  /** The code to render */
  @Input()
  text?: string;

  get finalText() {
    return this.object ? JSON.stringify(this.object, null, 2) : this.text;
  }
}
